
ifeq ($(CONFIG_PRODUCT_Z2),y)
obj-y += lenovo_lcd_effect_nt35521.o lenovo_lcd_effect_hx8394d.o
obj-y += z2/
else
obj-y += lenovo_lcd_effect_project.o
endif

obj-y += lenovo_lcd_effect.o lenovo_lcd_effect_mode.o lenovo_lcd_effect_color.o lenovo_fb.o

